### ISSUE TITLE
support for asian characters in the reference field

### ISSUE THREAD

**Issue by kebi-jp** [sobjornstad/TiddlyRemember#11]
The text field already supports it just fine

![image](https://user-images.githubusercontent.com/49175327/89164043-81b0d980-d5b1-11ea-9f74-70e5df847354.png)

**Comment by sortega** [comment]
This is because both the link and the anchor text are url-encoded.

**Comment by kebi-jp** [comment]
Is there a way I can preserve my Tiddler name or tags when importing? Not knowing the context of certain cards makes it difficult to answer

**Comment by sobjornstad** [comment]
The tiddler name shows up in the reference bit when it's working. For tags, you can set up a [mapping tiddler](https://sobjornstad.github.io/TiddlyRemember/#Mapping%20tiddlers) that says `[tags[]]` to pass through your TiddlyWiki tags to your Anki cards.

For both of these, you could edit the card template to show them on the front side of the card if you want that as context when you are answering. Changing the fields of the TiddlyRemember note types will make TiddlyRemember mad, but card template changes are fine.

I am not sure offhand why your reference text is not importing correctly. URL-encoding the tiddler names is a requirement to make the tiddlers export to files correctly, but it should not be retrieving the tiddler name from the filename. I'll have more luck reproducing it if you can provide me with a wiki containing a few tiddlers that don't work.

**Comment by sobjornstad** [comment]
Never mind, I'm just a doofus and didn't ever decode the text after reading the filename. I'll get a fix out this afternoon.

**Comment by sobjornstad** [comment]
Let me know if updating to 1.1.1 in Anki doesn't fix the problem for you.

**Comment by kebi-jp** [comment]
I updated the plugin and it worked. Thanks so much for the fast fix!
