### ISSUE TITLE
Anki import images from link source

### ISSUE THREAD

**Issue by kebifurai** [sobjornstad/TiddlyRemember#13]
Is there a way I can write the "img" string directly into the HTML code of the anki card??

![image](https://user-images.githubusercontent.com/49175327/89239651-bd40b780-d634-11ea-8a27-428617d7e01b.png)

**Comment by sobjornstad** [comment]
No, this is currently not possible as all HTML is stripped when moving over to Anki. That's something I want to improve, see #3.

**Comment by kebifurai** [comment]
I found a workaround by using HTML codes like this:

`&lt;img src=&quot;EXTERNAL LINK HERE`
`&quot; width=&quot;300px&quot;&gt;`

The line break is necesarry for it to work properly.

**Comment by sobjornstad** [comment]
Interesting, that sounds like a bug if it's possible. Please don't rely on that continuing to work in the next version. I am planning proper support for this in the next release.

**Comment by sobjornstad** [comment]
This should be fully supported using normal unescaped HTML in just-released 1.2. Let me know if anything doesn't work for you.
