### ISSUE TITLE
Changing the content of the "Reference" field in Anki

### ISSUE THREAD

**Issue by kebifurai** [sobjornstad/TiddlyRemember#15]
How can I change the content that goes to the "Reference" field in Anki?
By default it's "Tiddler title/ID" but I want to change it to another format, what lines of code should I change to achieve this?

**Comment by sobjornstad** [comment]
> How can I change the content that goes to the "Reference" field in Anki? By default it's "Tiddler title/ID"

Actually it's not, unless there's a bug I'm not aware of. The `Reference` field contains only the tiddler title. The text of the reference is put together on the card template in Anki:

```
<div class="note-id">
    {{#Permalink}}
        [<a href="{{text:Permalink}}">{{Wiki}}/{{Reference}}</a> {{ID}}]
    {{/Permalink}}
    {{^Permalink}}
        [{{Wiki}}/{{Reference}} {{ID}}]
    {{/Permalink}}
</div>
```

So what you see on the cards is a combination of the wiki name (set in the add-on settings), the tiddler name (whether hard reference or soft reference -- in the `Reference` field), and the ID (in the `ID` field).

As long as you don't want a different piece of information than the ones in these fields, you don't have to change any code -- just edit the card templates of the two TiddlyRemember note types in your collection. It's fine to edit the card templates, just be aware that future updates to TiddlyRemember might require minor manual work to merge the changes. Just don't create new fields or delete or reorder existing fields; that will make TiddlyRemember get angry at you and refuse to sync.

**Comment by kebifurai** [comment]
Thanks for the info, I changed some code in the remembercz and rememberq toolbars, so thats why I was seeing the tiddler title before the ID.
By the way I think that manual hard references are not working as intented.
I see this in tiddly wiki:
![image](https://user-images.githubusercontent.com/49175327/89791869-cd89f280-db5e-11ea-923c-637d5ed47fb6.png)

But after the anki sync the field doesn't include the hard reference:
![image](https://user-images.githubusercontent.com/49175327/89792202-2e192f80-db5f-11ea-9d8a-69c966c3dd10.png)

**Comment by kebifurai** [comment]
I did some test and the reference doesn't work only when using macros.

ex: 
reference=<<stream-root-title>> doesnt work
reference="reference" does work

**Comment by sobjornstad** [comment]
Where did you define `stream-root-title`? When TiddlyRemember is rendering tiddlers to create Anki notes, it does not use the standard template, so it doesn't necessarily have access to all the same macros that the standard UI template does. It should, however, be able to access any normally defined global macros, and I'd be surprised if local ones didn't work, so I'm curious how you did this one.

**Comment by sobjornstad** [comment]
I've confirmed that in the unmodified TiddlyRemember in my wiki, this works with a constant macro and with a macro referencing a variable, both with the macro in the same tiddler as the list widget and with the macro in a separate tiddler tagged `$:/tags/Macro` to make it a global macro. Examples:

```
\define myref()
Test
\end

<$list filter="[tag[Driving]]">
    <$macrocall $name=rememberq id={{!!created}} question={{!!title}} answer={{!!text}} reference=<<myref>> />
</$list>
```

```
\define myref()
The tiddler $(title)$
\end

<$list filter="[tag[Driving]]">
	<$set name=title value={{!!title}}>
    <$macrocall $name=rememberq id={{!!created}} question={{!!title}} answer={{!!text}} reference=<<myref>> />
  </$set>
</$list>
```

**Comment by kebifurai** [comment]
Thanks for the reply, the problem was that `<<stream-root-title>>` wasn't returning plain text but something else.
