### ISSUE TITLE
Non-ascii characters get garbled

### ISSUE THREAD

**Issue by sortega** [sobjornstad/TiddlyRemember#19]
With questions including non-ascii characters:

```
<<rememberq "20200923152852640"
	"What 'élan vital' means?"
	"The 'vital force' that 'explains' biology and that inorganic matter lacks">>
```

The text is garbled during the import to Anki:
<img width="710" alt="imagen" src="https://user-images.githubusercontent.com/259587/94241626-2944eb00-ff15-11ea-89ad-b23afe517f01.png">

**Comment by sobjornstad** [comment]
Hey sortega,

From past experience, I'm guessing this is an issue related to the locale configured on your computer and I won't be able to reproduce it on mine if I try. :-) But there's probably a place where I can force specific settings to avoid the issue. What operating system and language settings are you using?

**Comment by sobjornstad** [comment]
Confirmed that this is working OK for me, so if you have more details about your OS as described above, that would be very helpful.

**Comment by sortega** [comment]
My Language & Region settings for OS X are:

* Preferred languages: English (Ireland), Español (Spain), English
* Region: Spain
* First day of week: Monday
* Calendar: Gregorian

In the terminal, I have these env vars:

```
LC_TERMINAL_VERSION=3.3.12
LC_CTYPE=UTF-8
LC_TERMINAL=iTerm2
LC_ALL=en_US.utf-8
```

I think everything should be using UTF-8...

**Comment by sortega** [comment]
Thanks for accepting the patch
