### ISSUE TITLE
v1.2.0 bump in TW plugin

### ISSUE THREAD

**Issue by crazko** [sobjornstad/TiddlyRemember#23]
Thanks for the new release! You probably forgot to bump version in `tw-plugin/plugin.info`. Update cannot be done:

![image](https://user-images.githubusercontent.com/1255989/94657659-0bef9280-0302-11eb-9c4c-90d345525474.png)

**Comment by sobjornstad** [comment]
Thanks, I forgot this spot due to a typo in my release instructions and then missed the problem because I only tested the install in a folder wiki (which worked fine). It should be working now, and I've updated the instructions and my smoke tests to avoid this issue in the future.

**Comment by crazko** [comment]
Thanks, works like a charm!

**Comment by sobjornstad** [comment]
Adding commit cross-references since I forgot to include the issue number: 1f03bbd9f80fba40b982ed0dd58a2d8a975a1d53, 86c9a3949ab1d0bcf671a82947fae6407f164b53.
