### ISSUE TITLE
Anki not syncing

### ISSUE THREAD

**Issue by aggoi1234** [sobjornstad/TiddlyRemember#25]
Hello, 

I followed the installation instructions on the TiddlyRemember wiki (so I dragged the plugin from there) and I got this error when trying to sync with my file: 

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-09 04:35:39

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 58, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Aqua8\\AppData\\Roaming\\npm\\tiddlywiki.cmd', '--output', 'C:\\Users\\Aqua8\\AppData\\Local\\Temp\\tmp5v0mhgnd\\render', '--render', '[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]]', '[encodeuricomponent[]addsuffix[.html]]', 'text/html', '$:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\__init__.py", line 142, in join_thread
    raise self.extract_thread.exception
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\__init__.py", line 60, in run
    self.notes = twimport.find_notes(
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 188, in find_notes
    _render_wiki(tw_binary, wiki_folder, render_location, filter_)
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 145, in _render_wiki
    _invoke_tw_command(cmd, wiki_path, "render wiki")
  File "C:\Users\Aqua8\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 69, in _invoke_tw_command
    raise Exception(f"Failed to {description}: return code {proc.returncode}.\n"
Exception: Failed to render wiki: return code 1.
$ C:\Users\Aqua8\AppData\Roaming\npm\tiddlywiki.cmd --output C:\Users\Aqua8\AppData\Local\Temp\tmp5v0mhgnd\render --render [type[text/vnd.tiddlywiki]] [type[]] +[!is[system]] [encodeuricomponent[]addsuffix[.html]] text/html $:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable

undefined:1

--------------

I saw TiddlyRememberParseable in the first error and checked it out. The content says "Recursive transclusion error in transclude widget." I have tried installing TiddlyRemember in an empty wiki and the error is still there. Can you fix this or is it a problem on my end?

**Comment by sobjornstad** [comment]
"Recursive transclusion error in transclude widget" is an expected message to get when you look at that template, it does not mean anything is wrong (it only displays properly when it's used as a template to render another tiddler). Anyway, I don't think that tiddler has anything to do with this error -- it just happens to be the last part of the command line that is failing.

The output TiddlyWiki is giving you, `undefined:1`, isn't very helpful here. It might be related to [this issue](https://github.com/Jermolene/TiddlyWiki5/issues/2509).

A couple questions:

* Are you using a folder wiki hosted on Node, or a file (from URL or on your computer)?
* How did you install the TiddlyRemember plugin (by dragging and dropping it into the wiki? globally on Node? in the plugins/ subdirectory of a folder wiki?).
* What is the output of `C:\Users\Aqua8\AppData\Roaming\npm\tiddlywiki.cmd --version` at a command line (such as the "Command Prompt" application in Windows)?

**Comment by aggoi1234** [comment]
Thank you for responding quickly. I used a file on my computer, I dragged and dropped TiddlyRemember to install, and the output is 5.1.22.

**Comment by aggoi1234** [comment]
I've tried syncing Anki with blank wiki and it worked. I'm thinking that this could be a plugin incompatibility problem.

**Comment by sobjornstad** [comment]
If you are able to break down the wiki that isn't working into something you're comfortable sharing, I can take a look and see if I spot anything. There's likely something invalid in there, or maybe some weird characters in a title or something like that, that TiddlyWiki doesn't like. You can attach it here or email me (contact at sorenbjornstad.com).

**Comment by aggoi1234** [comment]
So I tried bundling all of my tiddlers and importing them into the blank wiki (with all the plugins) - there's no problems with syncing. I suppose the error will just remain a mystery...

Edit: thanks for the offer though, I appreciate it.
