### ISSUE TITLE
Support syncing some subset of formatting to Anki

### ISSUE THREAD

**Issue by sobjornstad** [sobjornstad/TiddlyRemember#3]
We currently strip all HTML within macro parameters, but Anki supports HTML on cards, so this is not necessary, and the ability to preserve some formatting would be nice. The challenge will be stripping or updating things like internal links so that the Anki notes are not full of unusable junk.

**Comment by linonetwo** [comment]
For links, maybe they can be prefixed with wiki URL when importing from the tw.

**Comment by sobjornstad** [comment]
Most HTML is supported in 1.2. [Creating notes in TiddlyRemember](https://sobjornstad.github.io/TiddlyRemember/#Creating%20notes%20in%20TiddlyRemember) describes what is and is not supported.

If you find something that should be supported but doesn't show up, shows up garbled, or otherwise needs work, please open a new issue.
