### ISSUE TITLE
Error when datepicker plugin is enabled

### ISSUE THREAD

**Issue by samjohn24** [sobjornstad/TiddlyRemember#34]
Hi,

First of all, many thanks for coding this plugin, it has been very helpful.

I've run into the below error when I tried to use TiddlyRemember and the datepicker plugin (https://github.com/kixam/TW5-datePicker) together. If I disable the datepicker plugin before to synchronize, the error disappears. 

Regards,
Sammy

```console
Anki 2.1.38 (355e4cd5) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-01-24 02:14:22
Add-ons possibly involved: ⁨TiddlyRemember⁩

Caught exception:
Traceback (most recent call last):
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/twimport.py", line 61, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/tiddlywiki', '--output', '/tmp/tmpsnzwgbu6/render', '--render', '[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]!tag[tmap]]', '[encodeuricomponent[]addsuffix[.html]]', 'text/html', '$:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/__init__.py", line 187, in join_thread
    if self.handle_thread_exception():
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/__init__.py", line 175, in handle_thread_exception
    raise exc
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/__init__.py", line 62, in run
    self.notes = twimport.find_notes(
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/twimport.py", line 201, in find_notes
    _render_wiki(tw_binary, wiki_folder, render_location, filter_)
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/twimport.py", line 158, in _render_wiki
    _invoke_tw_command(cmd, wiki_path, "render wiki")
  File "/home/scarbajali/.local/share/Anki2/addons21/60456529/twimport.py", line 72, in _invoke_tw_command
    raise RenderingError(
60456529.oops.RenderingError: Failed to render wiki: return code 1.
$ /usr/local/bin/tiddlywiki --output /tmp/tmpsnzwgbu6/render --render [type[text/vnd.tiddlywiki]] [type[]] +[!is[system]!tag[tmap]] [encodeuricomponent[]addsuffix[.html]] text/html $:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable

LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "−" (8722) [unknownSymbol]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:160
	var doc = options.document || document;
	                              ^

ReferenceError: document is not defined
    at Object.$tw.utils.domMaker (/usr/local/lib/node_modules/tiddlywiki/boot/boot.js:160:32)
    at DatePickerWidget.render ($:/plugins/kixam/datepicker/widget.datepicker.js:51:29)
    at VarsWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:393:15)
    at VarsWidget.render ($:/core/modules/widgets/vars.js:43:7)
    at MacroCallWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:393:15)
    at MacroCallWidget.render ($:/core/modules/widgets/macrocall.js:33:7)
    at SetWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:393:15)
    at SetWidget.render ($:/core/modules/widgets/set.js:33:7)
    at SetWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:393:15)
    at SetWidget.render ($:/core/modules/widgets/set.js:33:7)
```

**Comment by sobjornstad** [comment]
Are you sure your wiki is loading properly with both plugins installed, if you do a full reload of the page? This doesn't look like anything related to TiddlyRemember, but rather that TiddlyWiki is failing to load your wiki at all with the date-picker plugin installed, and TiddlyRemember is thus unable to sync it.

**Comment by samjohn24** [comment]
Yes, I'm quite sure. I have installed both plugins in TiddlyWiki (Node.js) and there is no error. The error only appears when I try to synchronize it with Anki. But as I said above, if I disable the DatePicker plugin, the error disappears. So my current flow is:

1. Disable DatePicker (not to uninstall)
2. Synchronize TiddlyRemember in Anki.
3. Enable DataPicker again.

**Comment by sobjornstad** [comment]
The error didn't happen for me when I merely installed the plugin, but on further investigation it does happen when I include a date-picker widget in a tiddler that TiddlyRemember is rendering. It appears that this is a [known bug in the date picker plugin](https://github.com/kixam/TW5-datePicker/issues/12). As I suspected before, TiddlyRemember isn't actually involved here at all, except that it has to render your tiddlers to extract the content and the date picker widget isn't rendering correctly. The reason you don't see this when interactively using your wiki is that the bug only crops up when running noninteractively under Node.js without access to a browser.

So if you really want it fixed, you might visit the thread on that plugin and poke over there, but it sounds like the author of the plugin doesn't know enough about TiddlyWiki on Node.js to fix it themselves, so unless you have that experience, we might be stuck waiting until someone else who does comes along and wants to use the plugin like this!

## Workarounds

If you don't ever use a date picker and TiddlyRemember macros on the same tiddler, you could work around the issue by setting the filter in TiddlyRemember's [Anki settings](https://sobjornstad.github.io/TiddlyRemember/#Configuring%20the%20Anki%20add-on) to a value that excludes any tiddlers that might end up with date picker widgets rendering within them. You might even be able to do it dynamically by finding the text `$edit-date` or some such within the text of tiddlers being considered by the filter.

If you want to use them on the same tiddler, a dumb hack would be to wrap all references to the `$edit-text` widget in a `$list` widget, like this, such that TiddlyWiki only tries to render the date picker widget if a variable doesn't match a value:

```
<$list filter="[<myvar>match[myvalue]]">
  <$edit-date field="mydate"/>
</$list>
```

You would then need to make `myvar` set to `myvalue` somewhere on the ViewTemplate that transcludes tiddlers in the story river, so that your date picker widgets would appear (this would almost certainly require overriding a shadow tiddler). TiddlyRemember uses a custom template, `$:/plugins/sobjornstad/TiddlyRemember/templates/TiddlyRememberParseable`, to render tiddlers and search them for notes, so the variable would stay undefined there and avoid displaying the widget when being read by Node.js.

**Comment by sobjornstad** [comment]
(Note to self: in a future version of TR, it might be handy to set a variable within the `TiddlyRememberParseable` template indicating that TiddlyRemember is running. Then it wouldn't be quite so ugly a hack if you needed to include conditional logic like this.)

**Comment by samjohn24** [comment]
Thanks for the detailed reply. I will try out your workaround. As in my case `datepicker` is being called by another plugin (ToDoNow), I've also opened an issue in the caller plugin.

**Comment by jasonmhoule** [comment]
Another workaround I am playing with is to make shadow tiddlers of offending module scripts and add `if (!$tw.browser) { return; }` as the first line under a widget's `.render` method (and also in a few other spots that have caused trouble with TiddlyRemember sync). I only use a browser TW so I'm not sure if this would screw up a wiki running on node (I suspect it might), but it gets the job done for my TiddlyRemember workflow, and I can use TR and other widgets without wrapping them as suggested above.

**Comment by sobjornstad** [comment]
A variable `tr-rendering` will be available in the next release to easily distinguish when TiddlyRemember is running.
