### ISSUE TITLE
Feature Request: Copy the tiddler tags to the Anki notes tags

### ISSUE THREAD

**Issue by samjohn24** [sobjornstad/TiddlyRemember#35]
Not sure if this makes sense for other users, but I think to better organize your generated cards in Anki and maybe use Filtered Decks it would be interesting  to copy automatically the tiddler tags into the generated Anki notes tags.

Maybe it shouldn't be a default behavior, but something the user can enable optionally.

**Comment by sobjornstad** [comment]
This is supported via [mapping tiddlers](https://sobjornstad.github.io/TiddlyRemember/#Mapping%20tiddlers). That page has a full explanation of all the options (you can get much more complicated behavior than this!), but to get the effect you mention, you would set the text of the tiddler `$:/config/TiddlyRemember/TagMapping` to `[tags[]]`.

**Comment by samjohn24** [comment]
I've just tried out this feature. It works very well. Thanks!
