### ISSUE TITLE
Support backlink

### ISSUE THREAD

**Issue by linonetwo** [sobjornstad/TiddlyRemember#39]
Currently, link inside QA won't be discover by the backlink filter, so won't showup in any double link plugin. Is this addressable?

**Comment by sobjornstad** [comment]
No, it is not. Links generated by macros are inherently [soft links](https://tiddlywiki.com/#Hard%20and%20Soft%20Links). This is a limitation of TW itself, so there's unfortunately nothing I can do to change it.

I'd love to see ways to relate tiddlers without having a direct link within the tiddler in core, but that's obviously beyond the scope of TiddlyRemember.
