### ISSUE TITLE
"." Wiki Name Error

### ISSUE THREAD

**Issue by BrickFrog** [sobjornstad/TiddlyRemember#42]
I skimmed the closed issues, but not sure if it was mentioned that a "." in the title causes a 'invalid "" name error' when syncing

e.g, for those using their TW's as a website (blah.com, blah.io, etc. etc.) and use the name in the config section of TiddlyRemember

**Comment by sobjornstad** [comment]
I went and tried adding a wiki called `Test.Wiki`, and it worked fine for me.

To help me narrow this down, can you provide:

* Your operating system and Anki version.
* A screenshot of the settings in the Add-ons -> TiddlyRemember -> Config dialog that are causing the issue.
* A screenshot or the exact text of the error message.

Thanks!

**Comment by BrickFrog** [comment]
I just did some testing, creating new a new vanilla TW + node.js folder tiddlywiki + . in name and not and wasn't able to replicate. 

Weirdly, it didn't even cause a Python stacktrace, it just ended up with only "invalid "" name error", which I  can't screenshot as I have seem to fixed (Windows 10 + Anki 2.1.44). 

Only action taken on my part was seeming changing it away from the name, -then- I had to remove two plugins (DatePicker, which I saw there were issues with, and Tidgraph) to get it working normally. After those were removed + all their usage removed,  I can't replicate

Seems like this is too much of an edge case to keep open, and on the off chance someone runs into it they'll be able to search the issues for "name error" and find this.

**Comment by sobjornstad** [comment]
I wonder if you actually ran into this:
https://github.com/sobjornstad/TiddlyRemember/issues/41

**Comment by BrickFrog** [comment]
It's possible it could be a vestige of it, I might've accidently added it originally, but it goes away if you correct it(?)

I ended up removing / re-adding multiple times and it didn't seem to correct itself until I removed the plugins that were problematic.

I don't think the name had anything to do with the error now, I think it might've just screwed up the reporting of it, while the underlying plugins were the real issue.
