### ISSUE TITLE
[Feature request] Improve the flexibility and use of inline cloze deletions

### ISSUE THREAD

**Issue by SonephetR2** [sobjornstad/TiddlyRemember#46]
Inline cloze deletions are terribly useful and I've been using them abundantly over the past months. I've tweaked a few things using shadow tiddlers and believe these changes could actually be useful for others:

* Adding a shortcut specifically for inline cloze deletions, without having to manually add the extra "inline" argument, or giving the option to simply default to "inline" from plugin options.
* Enabling easy change of the cloze-identifier (currently "{cloze:" and "}") to make them more discrete (I loved the default cloze-identifier initially, but now prefer simply using the coloured opening and closing braces).
* Adding the option to hide the `self-id` of the inline cloze deletions as the display becomes quite unseemly when having more than one inline cloze deletions in a paragraph. This is easily done by changing the CSS with a `display: none` associated to the `tr-selfidentification` class though I guess there may be some trade-offs to this or you wouldn't have wanted this information displayed in the first place.

I'd gladly prepare a pull request for any or all of these if you believe they could make sense for a larger user base.

**Comment by sobjornstad** [comment]
Great suggestions! I'm on sabbatical right now and hoping to dig into a bunch of improvements to TiddlyRemember starting in perhaps the next couple of weeks, which will probably involve some broad design considerations, so let me plug these suggestions into there and see what I come up with.
