### ISSUE TITLE
Comments and Usage Questions

### ISSUE THREAD

**Issue by ohare93** [sobjornstad/TiddlyRemember#5]
Saw this reposted to [r/Anki](https://www.reddit.com/r/Anki/comments/gq4qzy/tiddlyremember_a_tool_to_link_tw5_to_anki/), and wanted to share my thoughts. Feel free to close this and/or redirect me to where I should have posted this.

>Get out of my brain, I was gonna make this 😉 Very nice stuff, I am glad to see a connection between two of my favourite applications. Thanks for your efforts!
>
>Do you get use out of it? I am curious how many cards you manage using this method. For myself the unidirectional sync, and lack of support for custom note types makes me unable to use this properly.
>
>What exactly is the use of the TiddlyWiki plugin? Just to setup the macro? Did you consider creating each Anki note as a Tiddler and search for them by tag using the TiddlyWiki API?
>
>This is how I was planning (and still do) to implement TiddlyWiki as a import/export type in my weekend project [Brain Brew](https://github.com/ohare93/brain-brew). I probably won't get round to that for a month or so, as I have other tasks to do first, but the benefits would be bi-directional syncing, using any note type, into/from Csv or CrowdAnki. No direct Anki add-on though, but it is possible.
>
>Anyways mate, good work 👍 I hope you and others get good use out of it. Hit me up if you want to chat Anki / TiddlyWiki syncing to death.

**Comment by sobjornstad** [comment]
Thanks for bringing this to my attention, I'll join the thread over there!
