### ISSUE TITLE
Auth basic password protected wiki not syncing

### ISSUE THREAD

**Issue by sortega** [sobjornstad/TiddlyRemember#57]
My wiki setup with a wiki password protected with auth basic is no longer working with the new release. This is the relevant error snippet with my password redacted:

```
Caught exception:
Traceback (most recent call last):
  File "http/client.py", line 871, in _get_hostport
ValueError: invalid literal for int() with base 10: '*******************@tiddlywiki.refeed.org'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 185, in join_thread
    if self.handle_thread_exception():
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 173, in handle_thread_exception
    raise exc
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/importer.py", line 57, in run
    self.notes = twimport.find_notes(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 248, in find_notes
    notes = _notes_from_paths(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 110, in _notes_from_paths
    notes.update(_notes_from_tiddler(tid_text, wiki, tid_name, warnings))
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twimport.py", line 134, in _notes_from_tiddler
    return TwNote.notes_from_soup(soup, wiki, tiddler_name, warnings)
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 147, in notes_from_soup
    notes.update(subclass.parse_html(
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 321, in parse_html
    pair = extract_media(media, pair, wiki, tiddler_name, warnings)
  File "/Users/sortega/Library/Application Support/Anki2/addons21/60456529/twnote.py", line 659, in extract_media
    with urlopen(open_src) as response:
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 1393, in https_open
  File "urllib/request.py", line 1319, in do_open
  File "http/client.py", line 1382, in __init__
  File "http/client.py", line 833, in __init__
  File "http/client.py", line 876, in _get_hostport
http.client.InvalidURL: nonnumeric port: '*********@tiddlywiki.refeed.org'
```

I have non-alphanumeric characters in there just in case it's useful.

**Comment by sortega** [comment]
I've modified the exception locally to have more information:

```
60456529.oops.ExtractError: Unable to retrieve media files from the Internet for 'EcologicalRationality' and source 'https://********@tiddlywiki.refeed.org:443/' and elem '<img src="" width="200"/>'. Please check your network connection and review the error below for more information if necessary.
```

The source for the EcologicalRationality tiddler is:

```
We humans are not strictly rational because evolution was not selecting for that but for being successful in our ancestral environment. Because of not having unlimited mental resources ([[BoundedRationality]]), [[heuristics|Heuristic]] that were adaptive were selected.

This means that we can be easily fooled by some heuristics that doesn't apply anymore.

Examples:

*Dysfunctional. If your neighbour talks to you about a tiger in the neolithic it's a sign they are a danger to consider, if your read about it in the press, it's [[AvailabilityBias]].
*Functional. We are naturally good at handling complex social norms. See variants of the [[WasonSelectionTask]] leveraging social cues.

<$details summary="Trivia">
<<rememberp "20211025192857175"
	"''Define'': Ecological Rationality"
	"''Definition'': When heuristics produce roughly the right outcomes for a given environment">>
<<rememberq "20211025191050620"
	"Who coined //ecological rationality//?"
	"Gerd Gigerenzer <br> [img width=200 [gerd_gigerenzer.jpg]]">>
</$details>
```

**Comment by sobjornstad** [comment]
That is strange! `extract_media` is the very first call in the `parse_html()` methods, before any other parts of the widget tree get mutated, so I don't know why it would be coming out blank. Maybe the `__repr__` of the BeautifulSoup element is displaying it as blank when it isn't because of malformed content? You could try printing `src` to the console right after line 640.

Am I assuming correctly that there is a colon in the middle of the string before the `@`, to separate your username from your password?

I don't know of an easy way off the top of my head to create a web server serving files from the local filesystem with HTTP basic auth (I normally use the `twistd` CLI but it doesn't appear to support this), so it's hard for me to test this scenario. Do you happen to know of something that I could spin up quickly?

**Comment by sortega** [comment]
I think this is related to image lazy loading, which I forgot I got configured.
However, if I disable it the wiki is not loading at all.

**Comment by sobjornstad** [comment]
Can you attach a version of the `meta.json` in the TiddlyRemember add-on folder? It would be helpful to see exactly what settings you're using. It'll be in the `addons21/60456529` folder within your Anki data folder. You'll want to redact your password out of it first.

When you say the wiki isn't loading at all, you mean it won't load within TiddlyRemember, or within your browser?

**Comment by sortega** [comment]
Sadly, I mean that images are so heavy that the request times out in the browser.

My meta.json (redacted):

```
{"name": "TiddlyRemember", "mod": 1636857675, "min_point_version": 45, "max_point_version": 49, "branch_index": 2, "config": {"defaultDeck": "General", "tiddlywikiBinary": "/Users/sortega/opt/tiddlywiki/node_modules/.bin/tiddlywiki", "schemaVersion": "1", "wikis": {"tiddlywiki": {"contentFilter": "[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]]", "path": "https://*****:****@tiddlywiki.refeed.org:443/", "permalink": "https://tiddlywiki.refeed.org/", "type": "url"}}}, "disabled": false, "conflicts": [], "update_enabled": true}
```

**Comment by sobjornstad** [comment]
So since you say you're using lazy-loading, are you running the Node.js version at that URL? That's actually not a scenario that's designed to be supported for the “URL” wiki type.

**Comment by sobjornstad** [comment]
I've confirmed on my own Node.js wiki that image syncing works OK with lazy-loading off.

**Comment by sortega** [comment]
Yes, I'm using Node.js to run a couple wikis in a server. Then I use nginx configured as a reverse proxy in front of them to offer SSL and Basic Auth.

I had a few test images in some tiddly remember macros for testing purposes before the update. Because it's only a few and it's easy to revert I've removed those images and syncing works again.

My plan is to replace lazy loading by having a daily script to externalize images and then try again. I'm closing the issue because now we now it has more to do with my setup than with the intended use of the plugin.

**Comment by sobjornstad** [comment]
Sounds good. For this size image database, externalized images are probably a better long-term solution anyway.

For you or anyone else who stumbles on this thread, I'd be happy to accept PRs to make lazy-loading work by somehow detecting it's in place and calling the TW API to retrieve them. I have never worked with that API and so don't know how that would function or even whether this is practical, but if you do and would find the feature helpful, feel free to implement!
