### ISSUE TITLE
Unable to sync/import tiddlers with moderately long titles in cyrillic. 

### ISSUE THREAD

**Issue by disto1311** [sobjornstad/TiddlyRemember#65]
Full bug report [here](https://pastebin.com/X0j0Sa9P) 

What I think are relevant excerpts: 

**1.**

 It looks like your wiki may contain a tiddler with an extremely long name, which cannot be synced due to limits on the length of a filename in your operating system. Please reduce the length of this tiddler name and then try syncing again. The exact length allowed will depend on your operating system and the language your tiddler title is written in, but should generally not be more than 200 characters (sometimes less).

Tiddler path: /var/folders/mg/nhb03std5537jk85fwpy31_00000gn/T/tmpuynyv5zu/render/%D0%9A%D0%BE%D0%BD%D1%84%D1%96%D0%B4%D0%B5%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D1%8F%20vs%20%D0%BA%D0%BE%D0%BC%D0%B5%D1%80%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%82%D0%B0%D1%94%D0%BC%D0%BD%D0%B8%D1%86%D1%8F.html

**2.** 

Rendering "Конфіденційна інформація vs комерційна таємниця" to "/var/folders/mg/nhb03std5537jk85fwpy31_00000gn/T/tmpuynyv5zu/render/%D0%9A%D0%BE%D0%BD%D1%84%D1%96%D0%B4%D0%B5%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D1%8F%20vs%20%D0%BA%D0%BE%D0%BC%D0%B5%D1%80%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%82%D0%B0%D1%94%D0%BC%D0%BD%D0%B8%D1%86%D1%8F.html"
node:internal/fs/utils:344
    throw err;
    ^

Error: ENAMETOOLONG: name too long, open '/var/folders/mg/nhb03std5537jk85fwpy31_00000gn/T/tmpuynyv5zu/render/%D0%9A%D0%BE%D0%BD%D1%84%D1%96%D0%B4%D0%B5%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%96%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D1%96%D1%8F%20vs%20%D0%BA%D0%BE%D0%BC%D0%B5%D1%80%D1%86%D1%96%D0%B9%D0%BD%D0%B0%20%D1%82%D0%B0%D1%94%D0%BC%D0%BD%D0%B8%D1%86%D1%8F.html'

**Comment by sobjornstad** [comment]
Sorry, I don't think there's much I can do about this – as the error message explains, it's a Windows limitation.

I will continue to consider other ways of selecting a filename for the exports (see #40 where this is also causing issues), but I'm not sure there is anything available as a TW filter other than URL encoding that's guaranteed to produce a unique name without any characters that could be illegal in filenames.
