### ISSUE TITLE
After update to  Anki desktop fails to sync Grok Tiddlywiki

### ISSUE THREAD

**Issue by sheridanmp** [sobjornstad/TiddlyRemember#66]
Below is the whole error message from Anki desktop.
When I ran it 2 days ago it said there was a plugin update so I updated. Anki then failed whenever it tried to "sync from Tiddlywiki" if the wiki was Grok Tiddlywiki. If it was removed from the list then the other wikis synced ok. I realized today that perhaps I needed to update TiddlyRemember in Grok so it is now 1.3.3 but the error still occurs.
From Anki: (and yes I did misspell Tiddly :-) in the path. Oh well )

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-21 12:22:50

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 71, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Sheridan\\AppData\\Roaming\\npm\\tiddlywiki.cmd', '--load', 'D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/groctiddly.html', '--savewikifolder', 'C:\\Users\\Sheridan\\AppData\\Local\\Temp\\tmpzk4w_29c\\wikifolder']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py", line 190, in join_thread
    if self.handle_thread_exception():
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py", line 178, in handle_thread_exception
    raise exc
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py", line 62, in run
    self.notes = twimport.find_notes(
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 221, in find_notes
    _folderify_wiki(tw_binary, wiki_path, wiki_folder, password)
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 62, in _folderify_wiki
    _invoke_tw_command(cmd, None, "folderify wiki")
  File "C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py", line 87, in _invoke_tw_command
    raise RenderingError(
60456529.oops.RenderingError: Failed to folderify wiki: return code 1.
(If this wiki is encrypted, did you forget to give the password?)
$ C:\Users\Sheridan\AppData\Roaming\npm\tiddlywiki.cmd --load D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/groctiddly.html --savewikifolder C:\Users\Sheridan\AppData\Local\Temp\tmpzk4w_29c\wikifolder

[1;31mError: No tiddlers found in file "D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/groctiddly.html"[0m

**Comment by sobjornstad** [comment]
Do you mind attaching a copy of your wiki?

**Comment by sheridanmp** [comment]
I tried but got a gmail "message too large" error. Suggestions?
Sher

**Comment by sobjornstad** [comment]
GTW should only be ~5MB, I think Gmail's limit is 25MB, so I'm a bit surprised by that unless you added a bunch of images to it.

Did you try clicking through to GitHub and attaching it there? Maybe it doesn't like receiving files via email. You can also try emailing it to me directly at `contact@sorenbjornstad.com`.

**Comment by sheridanmp** [comment]
Sent again, separate, and seems to have worked. But I didn't add anything
except some words in the email and a repeat of the error message.Oh well.
Isn't technology fun.
Sher

**Comment by sobjornstad** [comment]
The file you sent works for me.

I am on Anki 2.1.49, one version ahead of you, so you might try updating just in case that's the issue – though this version of the add-on definitely *should* be compatible with 2.1.48 too. But we all know how *should* works out with software.

Also, try upgrading the GTW file itself ([instructions](https://groktiddlywiki.com/read/#Upgrade)) – if you happened to start on version 1.2.0, that had a bug in it that 
prevented takeaways from syncing correctly (see [changes list](https://groktiddlywiki.com/read/#Changes)).

If neither of those things helps, can you send a screenshot of your settings for this wiki in Tools → Add-ons → TiddlyRemember?

**Comment by sheridanmp** [comment]
Hi Soren;

I am traveling so will not be able to try it out for a couple of days.
Thanks for the quick response.
Sher

**Comment by sheridanmp** [comment]
Hello Soren;
So I am still having failures.
The scenarios are/have been as follows:
Anki 2.1.48 Grok   1.0.2  original failure after upgrading the plugin in
Anki
Anki 2.1.48 Grok   1.2.2 after upgrading Grok via the updater program (what
I sent to you)
Anki 2.1.49 Grok   1.2.2 after upgrading Anki via regular update mechanism
(same wiki I sent to you)
Anki 2.1.49 Grok   1.2.2 after downloading a fresh copy of Grok from your
site.(error message below as well as screen capture you requested.)***
Anki 2.1.49 Grok    1.2.2 after wiping Anki completely (including removing
Appdata folders) and reinstalling. (I've included it's error message as the
second error message copy below and included the addon screenshot for it as
well, notice it only has Grok as a wiki) ####
Regards
Sher
====================
Error***
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools >
Add-ons menu item to disable some add-ons and restart Anki, repeating until
you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-23 22:06:31

Caught exception:
Traceback (most recent call last):
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 71, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command
'['C:\\Users\\Sheridan\\AppData\\Roaming\\npm\\tiddlywiki.cmd', '--load',
'D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html',
'--savewikifolder',
'C:\\Users\\Sheridan\\AppData\\Local\\Temp\\tmp39iw5dmx\\wikifolder']'
returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 190, in join_thread
    if self.handle_thread_exception():
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 178, in handle_thread_exception
    raise exc
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 62, in run
    self.notes = twimport.find_notes(
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 221, in find_notes
    _folderify_wiki(tw_binary, wiki_path, wiki_folder, password)
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 62, in _folderify_wiki
    _invoke_tw_command(cmd, None, "folderify wiki")
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 87, in _invoke_tw_command
    raise RenderingError(
60456529.oops.RenderingError: Failed to folderify wiki: return code 1.
(If this wiki is encrypted, did you forget to give the password?)
$ C:\Users\Sheridan\AppData\Roaming\npm\tiddlywiki.cmd --load
D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html
--savewikifolder C:\Users\Sheridan\AppData\Local\Temp\tmp39iw5dmx\wikifolder

[1;31mError: No tiddlers found in file
"D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html"
[0m

==================================
Error   ####
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the
Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat
until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-ons section of our support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-24 11:43:25

Caught exception:
Traceback (most recent call last):
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 71, in _invoke_tw_command
    proc = subprocess.run(cmd, cwd=wiki_path, stdout=subprocess.PIPE,
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command
'['C:\\Users\\Sheridan\\AppData\\Roaming\\npm\\tiddlywiki.cmd', '--load',
'D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html',
'--savewikifolder',
'C:\\Users\\Sheridan\\AppData\\Local\\Temp\\tmpk_yrmuje\\wikifolder']'
returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 190, in join_thread
    if self.handle_thread_exception():
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 178, in handle_thread_exception
    raise exc
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\importer.py",
line 62, in run
    self.notes = twimport.find_notes(
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 221, in find_notes
    _folderify_wiki(tw_binary, wiki_path, wiki_folder, password)
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 62, in _folderify_wiki
    _invoke_tw_command(cmd, None, "folderify wiki")
  File
"C:\Users\Sheridan\AppData\Roaming\Anki2\addons21\60456529\twimport.py",
line 87, in _invoke_tw_command
    raise RenderingError(
60456529.oops.RenderingError: Failed to folderify wiki: return code 1.
(If this wiki is encrypted, did you forget to give the password?)
$ C:\Users\Sheridan\AppData\Roaming\npm\tiddlywiki.cmd --load
D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html
--savewikifolder C:\Users\Sheridan\AppData\Local\Temp\tmpk_yrmuje\wikifolder

[1;31mError: No tiddlers found in file
"D:/Downloads/Programs/TidlyWiki/MyTiddlyWikis/GROKtiddlywikiFreshCopy.html"
[0m

**Comment by sobjornstad** [comment]
The screenshot didn't come through, can you try to upload it on the GitHub web interface or email it to me directly?

**Comment by sobjornstad** [comment]
The settings look right, and again, it is still working for me! If you want you could email the latest version of the wiki you got after the upgrade so I can double-check that one is right, too.

If you open up the `Takeaway Export List` tiddler in your copy of Grok TiddlyWiki, are takeaways showing up there? (They are for me, but maybe something is different on your end?) Also, try deleting everything in the Filter box in the add-on configuration dialog using Ctrl+A, Delete, and then type in the filter again -- possibly you could have gotten an invisible special character in there that's causing problems.

Can you verify the version of the TiddlyRemember plugin you have in Anki? If you find your [Anki file location](https://docs.ankiweb.net/files.html#file-locations) and then go into `addons21/60456529`, you should find a file called `util.py`. Line 14 should say `PLUGIN_VERSION = "1.3.3"` if you have the latest version.

**Comment by sheridanmp** [comment]
Good evening Soren;

I realized I haven't heard back from you since I sent you the response
regarding the plugin version and the copy of Groktiddly that I am using
presently as you requested.
As I got file size errors  I added your ***@***.*** email and resent but
perhaps something went wrong with that as well and you are actually still
waiting for me!!
Regards
Sheridan

**Comment by sheridanmp** [comment]
Thank you Soren. I won't get a chance for a couple of days but will try
each idea out then..

Regards
Sheridan

**Comment by sheridanmp** [comment]
Good afternoon Soren;

I did the npn update and that fixed the problem.  For the record and to
ensure no confusion:
I am presently running (after the update via npm update)

node-js: 14.7.6.

Groktiddlywiki:
Book version 1.2.2
TiddlyWiki version 5.2.1Anki:
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

Tiddlyremember:
DEFAULT_FILTER = '[type[text/vnd.tiddlywiki]] [type[]] +[!is[system]]'
PLUGIN_VERSION = "1.3.3"
COMPATIBLE_TW_VERSIONS = ["", "1.2.2", "1.2.3", "1.3.0", "1.3.1", "1.3.2",
"1.3.3"]

Thank you very much. I would never have resolved this without your patient
help.

Best regards
Sheridan

**Comment by sobjornstad** [comment]
Phew, I was running out of ideas! I’ll make sure to keep this in mind in 
case anyone else runs into it. I guess maybe I need to start checking 
the version number of the tiddlywiki npm package – though I’m not sure 
that would have helped here since I wasn’t aware there was some kind of 
incompatibility.

As Mark Dominus says, this computer stuff is amazingly complicated and I 
don’t know how anyone gets anything done!
