### ISSUE TITLE
Anki tags only appear if the tags exist in tiddlywiki

### ISSUE THREAD

**Issue by GameDungeon** [sobjornstad/TiddlyRemember#67]
I have a bunch of classes, and I have my anki set up to stick its tags at the top of the flashcard so I know the context it's talking about. With full class names it was taking up a lot of room, so I changed my tag mapping to return a shorthand. The issue is, TiddlyRemember only allows me to put tags that exist in my TiddlyWiki on my anki cards (as far as I can tell). I really wish this was not a limitation, because a bunch of useless tags floating around just makes a mess.

**Comment by sobjornstad** [comment]
I  don't think this is a limitation, unless I'm misunderstanding you; the filter language should let you add arbitrarily complex logic to determine what tags to include on your cards. Can you maybe explain / provide screenshots of your current tag mappings and where you're trying to pull the data from?

**Comment by GameDungeon** [comment]
Heres my current tag mapping:
> [tags[]] :intersection[[Class]tagging[]addsuffix[Notes]] +[removesuffix[Notes]get[short]]

if I remove the get[short] it works fine, but If it is there, it won't work unless I make chem also a tag instead of just chemistry.

**Comment by sobjornstad** [comment]
I can't reproduce the behavior you're seeing, but maybe I don't understand how your notes are laid out. Here's a video showing how I'm interpreting how you're expecting this to work:

https://user-images.githubusercontent.com/2313414/156455208-eafac701-9b2a-41a3-9f18-eb1ee01eecd1.mp4

**Comment by GameDungeon** [comment]
I'm going to close this now. Thanks for trying to help. I don't know what has changed, but I did the same steps I did earlier, and now it works.... 

( You did reproduce it exactly though :) )
