### ISSUE TITLE
Katex Chemical equations in Cloze answer not rendering correctly

### ISSUE THREAD

**Issue by PayneGitHub** [sobjornstad/TiddlyRemember#70]
Chemical formula typeset using Katex notations and included in Cloze answers do not render correctly in Anki.

For example, this close question with Katex chemical equation in close answer : 

```
<<remembercz "20220709174549335"
	"Water has a chemical formula {$$\ce{H2O}$$}">>
```

renders incorrectly in Anki:

Water has a chemical formula \( \ce{H2O \)}

Where as this cloze question using Katex :

```
<<remembercz "20220709172833918"
	"Water has a chemical formula {$$H_2O$$}">>
```
renders correctly:

Water has a chemical formula H<sub>2</sub>O

Any suggestion on fixing this?

**Comment by sobjornstad** [comment]
You need to escape the braces, or TiddlyRemember will think the occlusion ends after `H2O`: https://sobjornstad.github.io/TiddlyRemember/#Escaping%20braces

**Comment by sobjornstad** [comment]
@PayneGitHub Just checking, did this resolve your issue?
