### ISSUE TITLE
Optional support for local filesystem images

### ISSUE THREAD

**Issue by gabrielmontagne** [sobjornstad/TiddlyRemember#72]
As the next step for #20, 

Could local images that were  linked with `[img[./files/something.png]]` tags, for node js setups, be  "figured out" from the `permalink`?  Where `./files/something.png` could be expanded to `http://localhost:8080/files/something.png` - if that's the permalink - and fetched from there?   Most of my images are local screenshots, etc. and I'd love to be able to use them on my TiddlyRemember cards.

Thanks!

**Comment by sobjornstad** [comment]
#20 is complete and all images should be getting imported into Anki's media folder ­in recent versions of TiddlyRemember – is that not happening for you?

**Comment by gabrielmontagne** [comment]
Not really, no.  Please note that I'm not using `file://` URLs, but directly `./file/etc.png`, 

![image](https://user-images.githubusercontent.com/95913/183314857-f3606a03-2cb1-4385-9ef6-96b33c806bf7.png)

**Comment by sobjornstad** [comment]
I see, I misread the request. Is your expectation that the server would have to be running and it would fetch the image directly from the URL? I'm not sure that's the right way to go about this if this is a File or Folder wiki – the permalink is currently an optional setting and it doesn't feel quite right to have it have an impact on where content is supposed to be fetched from.

In your setup, you have a `files` directory right inside the folder next to the `tiddlywiki.info`, right? Can't we just look for it there?

**Comment by gabrielmontagne** [comment]
I see what you're saying, and agree. It does feel kludgy and overloads and expects too much.

> In your setup, you have a files directory right inside the folder next to the tiddlywiki.info, right? Can't we just look for it there?

It is, yes, right next to the `tiddlywiki.info`, and I think that's somewhat standard for the node.js setup.  Yes.  We could just read it from there!

**Comment by gabrielmontagne** [comment]
... and maybe we don't have to bake `files` explicitly, but perhaps you could assume that all local looking paths can be assumed to be relative from where the `.info` file is?

**Comment by sobjornstad** [comment]
We actually already have code for this, I just overlooked this case and didn't say what to do for folder wikis. Can you try this version? There's no manifest included in here, so you'll need to extract it manually to a folder in your Anki add-ons folder.

[tr.zip](https://github.com/sobjornstad/TiddlyRemember/files/9278014/tr.zip)

**Comment by gabrielmontagne** [comment]
It worked perfectly @sobjornstad.  Good stuff! :+1:

**Comment by sobjornstad** [comment]
This will be in the next release.
